#!/usr/bin/env python3
"""Fetch the latest k6 performance test run status from GitHub Actions API.

Writes data/projects/k6-performance-tests/latest.json in the normalised
schema used by other fetch scripts so the dashboard card renders consistently.

When dispatched with a k6-json artifact, real metrics (P95 response time,
error rate, check pass rate) are parsed and displayed on the live site card.
Without an artifact, the script falls back to GitHub API run status only.

Usage (CI — direct dispatch with artifact):
    python scripts/fetch_k6_status.py \\
        --output-dir data/projects \\
        --run-id "$RUN_ID" \\
        --run-url "$RUN_URL" \\
        --results-json incoming/k6-json/k6-results.json

Usage (CI — polling latest run):
    python scripts/fetch_k6_status.py --output-dir data/projects

Usage (local — reads GITHUB_TOKEN env var if --token not supplied):
    python scripts/fetch_k6_status.py
"""
from __future__ import annotations

import argparse
import io
import json
import os
import sys
import urllib.error
import urllib.request
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO = "DaniHogg/k6-performance-tests"
WORKFLOW = "performance.yml"
BRANCH = "main"

# Scenario labels shown as "suite" rows when no per-test artifact is available.
_FALLBACK_SUITES = [
    ("baseline", "Baseline (10 VUs × 30s)"),
    ("ramp-up",  "Ramp-Up (1 → 50 VUs over 3.5 min)"),
    ("soak",     "Soak (20 VUs × 5 min)"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fetch k6 performance test CI status")
    parser.add_argument("--output-dir", default="data/projects")
    parser.add_argument(
        "--token",
        default=os.environ.get("SOURCE_REPO_TOKEN") or os.environ.get("GITHUB_TOKEN", ""),
    )
    parser.add_argument("--branch", default=BRANCH)
    parser.add_argument("--history-limit", type=int, default=5)
    parser.add_argument("--run-id", default="")
    parser.add_argument("--run-url", default="")
    parser.add_argument("--commit-sha", default="")
    parser.add_argument("--results-json", default="")
    return parser.parse_args()


# ---------------------------------------------------------------------------
# GitHub API helpers
# ---------------------------------------------------------------------------

def gh_get(path: str, token: str) -> dict:
    url = f"https://api.github.com{path}"
    req = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        **({"Authorization": f"Bearer {token}"} if token else {}),
    })
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as exc:
        print(f"GitHub API error {exc.code} for {url}: {exc.read().decode()[:200]}", file=sys.stderr)
        raise


def gh_get_bytes(url: str, token: str) -> bytes:
    # GitHub artifact download redirects to Azure Blob Storage.
    # The blob URL must be fetched without the Authorization header.
    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, req, fp, code, msg, headers, newurl):
            return None

    opener = urllib.request.build_opener(_NoRedirect)
    req = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        **({"Authorization": f"Bearer {token}"} if token else {}),
    })
    try:
        with opener.open(req, timeout=20) as resp:
            return resp.read()
    except urllib.error.HTTPError as exc:
        if exc.code in (301, 302, 303, 307, 308):
            blob_url = exc.headers.get("Location")
            if not blob_url:
                raise
            with urllib.request.urlopen(blob_url, timeout=60) as resp:
                return resp.read()
        raise


def iso_now() -> str:
    return datetime.now(tz=timezone.utc).isoformat().replace("+00:00", "Z")


def conclusion_to_status(conclusion: str | None) -> str:
    mapping = {"success": "passed", "failure": "failed", "cancelled": "cancelled"}
    return mapping.get(conclusion or "", "unknown")


# ---------------------------------------------------------------------------
# k6-results.json parsing (generated by scripts/generate-k6-json.js)
# ---------------------------------------------------------------------------

def parse_k6_results(data: dict) -> tuple[dict, list[dict]]:
    """Parse the normalised k6-results.json produced by generate-k6-json.js."""
    status = data.get("status", "unknown")

    totals = {
        "passed":  data.get("totals", {}).get("passed",  0),
        "failed":  data.get("totals", {}).get("failed",  0),
        "skipped": 0,
        "errors":  0,
    }

    suites: list[dict] = []
    for s in data.get("suites", []):
        suite_metrics = s.get("metrics", {})
        notes_parts = []
        if suite_metrics:
            p95  = suite_metrics.get("http_req_duration_p95_ms")
            avg  = suite_metrics.get("http_req_duration_avg_ms")
            err  = suite_metrics.get("http_req_failed_rate")
            chk  = suite_metrics.get("checks_pass_rate")
            if p95  is not None: notes_parts.append(f"P95={p95}ms")
            if avg  is not None: notes_parts.append(f"avg={avg}ms")
            if err  is not None: notes_parts.append(f"error_rate={err:.2%}")
            if chk  is not None: notes_parts.append(f"checks={chk:.2%}")
        notes = "  ".join(notes_parts) if notes_parts else "Metrics derived from k6 handleSummary output."
        suite_totals = s.get("totals", {})
        reqs = suite_totals.get("requests", 0)
        suites.append({
            "suite_id":   s.get("suite_id", "k6"),
            "suite_name": s.get("suite_name", "k6 Test"),
            "status":     s.get("status", status),
            "totals": {
                "passed":  reqs if s.get("status") == "passed" else 0,
                "failed":  reqs if s.get("status") == "failed" else 0,
                "skipped": 0,
                "errors":  0,
            },
            "notes": notes,
        })

    return totals, suites


def parse_results_file(results_json: str) -> tuple[dict, list[dict]] | None:
    path = Path(results_json)
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    return parse_k6_results(data)


def parse_artifact(run_id: str, token: str) -> tuple[dict, list[dict]] | None:
    if not token:
        return None

    try:
        artifacts = gh_get(f"/repos/{REPO}/actions/runs/{run_id}/artifacts", token)
    except Exception as exc:
        print(f"Warning: could not fetch artifact list: {exc}", file=sys.stderr)
        return None

    for artifact in artifacts.get("artifacts", []):
        if artifact.get("name") != "k6-json" or artifact.get("expired"):
            continue

        archive_url = artifact.get("archive_download_url")
        if not archive_url:
            continue

        try:
            blob = gh_get_bytes(archive_url, token)
            with zipfile.ZipFile(io.BytesIO(blob)) as zf:
                for name in zf.namelist():
                    if name.endswith(".json"):
                        data = json.loads(zf.read(name).decode("utf-8"))
                        return parse_k6_results(data)
        except Exception as exc:
            print(f"Warning: failed to parse k6-json artifact: {exc}", file=sys.stderr)
            return None

    return None


# ---------------------------------------------------------------------------
# Fallback — no artifact available
# ---------------------------------------------------------------------------

def fallback_totals_and_suites(overall_status: str) -> tuple[dict, list[dict]]:
    note = "Per-metric counts unavailable: no k6-json artifact was found for this run."
    suites = [
        {
            "suite_id":   sid,
            "suite_name": sname,
            "status":     overall_status if overall_status in ("passed", "failed") else "unknown",
            "totals":     {"passed": 0, "failed": 0, "skipped": 0, "errors": 0},
            "notes":      note,
        }
        for sid, sname in _FALLBACK_SUITES
    ]
    return {"passed": 0, "failed": 0, "skipped": 0, "errors": 0}, suites


# ---------------------------------------------------------------------------
# Output builder
# ---------------------------------------------------------------------------

def build_latest_json(
    run: dict,
    history_runs: list[dict],
    totals: dict,
    suites: list[dict],
) -> dict:
    conclusion = run.get("conclusion")
    status = conclusion_to_status(conclusion)
    started   = run.get("run_started_at") or run.get("created_at")
    completed = run.get("updated_at")
    run_id    = str(run["id"])
    run_url   = run["html_url"]
    branch    = run.get("head_branch", BRANCH)
    commit_sha = run.get("head_sha", "")

    duration_seconds = 0
    if started and completed:
        fmt = "%Y-%m-%dT%H:%M:%SZ"
        try:
            duration_seconds = int(
                (datetime.strptime(completed, fmt) - datetime.strptime(started, fmt)).total_seconds()
            )
        except ValueError:
            pass

    history = [
        {
            "run_id":       str(h["id"]),
            "status":       conclusion_to_status(h.get("conclusion")),
            "completed_at": h.get("updated_at"),
            "run_url":      h["html_url"],
        }
        for h in history_runs
    ]

    return {
        "$schema_version": "1.0.0",
        "last_refreshed_at": iso_now(),
        "project": {
            "id":             "k6-performance-tests",
            "name":           "k6 Performance Testing",
            "frameworks":     ["k6", "javascript"],
            "repository_url": f"https://github.com/{REPO}",
        },
        "latest": {
            "run_id": run_id,
            "source": {
                "provider": "github-actions",
                "workflow": "k6 Performance Tests",
                "branch":   branch,
                "commit_sha": commit_sha,
                "run_url":  run_url,
            },
            "status":           status,
            "started_at":       started,
            "completed_at":     completed,
            "duration_seconds": duration_seconds,
            "totals":  totals,
            "suites":  suites,
        },
        "history": history,
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    if not args.token:
        print(
            "Warning: no GitHub token supplied. Unauthenticated requests are rate-limited to 60/hour.",
            file=sys.stderr,
        )

    history_data = gh_get(
        f"/repos/{REPO}/actions/workflows/{WORKFLOW}/runs"
        f"?branch={args.branch}&per_page={args.history_limit + 3}&status=completed",
        args.token,
    )
    history_pool = history_data.get("workflow_runs", [])
    if not history_pool:
        print("No completed workflow runs found.", file=sys.stderr)
        sys.exit(1)

    if args.run_id:
        latest_run = gh_get(f"/repos/{REPO}/actions/runs/{args.run_id}", args.token)
    else:
        latest_run = history_pool[0]

    if args.run_url:
        latest_run["html_url"] = args.run_url
    if args.commit_sha:
        latest_run["head_sha"] = args.commit_sha
    if args.branch:
        latest_run["head_branch"] = args.branch

    history_runs = [
        h for h in history_pool if str(h.get("id")) != str(latest_run.get("id"))
    ][: args.history_limit]

    # 1. Try dispatched results file (fastest, most accurate)
    parsed = parse_results_file(args.results_json) if args.results_json else None
    # 2. Try downloading artifact from GitHub
    if not parsed:
        parsed = parse_artifact(str(latest_run.get("id")), args.token)
    # 3. Fall back to API-only status
    if parsed:
        totals, suites = parsed
    else:
        totals, suites = fallback_totals_and_suites(
            conclusion_to_status(latest_run.get("conclusion"))
        )

    output = build_latest_json(latest_run, history_runs, totals, suites)

    out_path = Path(args.output_dir) / "k6-performance-tests" / "latest.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")
    print(f"Written {out_path}  status={output['latest']['status']}  run={output['latest']['run_id']}")


if __name__ == "__main__":
    main()
